api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/packages/api_platform/']
    collection:
        pagination:
#            enabled: false
#            client_enabled: true
#            enabled_parameter_name: pagination
            page_parameter_name: _page
#            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 10
            partial: true
            client_partial: true
            partial_parameter_name: '_partial'
