App\Entity\BlogPost:
  attributes:
    normalization_context:
      groups: ['get']

    denormalization_context:
      groups: ['post']

  itemOperations:
    get:
      normalization_context: {groups: ['get-blog-post-with-author']}
    put:
      access_control: is_granted('ROLE_EDITOR', object) or (is_granted('ROLE_WRITER', object) and object.getAuthor() === user)

  collectionOperations:
    get:
      normalization_context: {groups: ['get-blog-post-with-author']}
    post:
      access_control: is_granted('ROLE_WRITER', object)

  properties:
    comment:
      subresource:
        resourceClass: 'App\Entity\Comment'
