App\Entity\BlogPost:
  attributes:
    normalization_context:
      groups: ['get']

    denormalization_context:
      groups: ['post']

  itemOperations:
    get:
      normalization_context: {groups: ['get-blog-post-with-author']}
    put:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object) and object.getAuthor() === user

  collectionOperations:
    get:
      normalization_context: {groups: ['get-blog-post-with-author']}
    post:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object)

  properties:
    comment:
      subresource:
        resourceClass: 'App\Entity\Comment'
