App\Entity\BlogPost:
  attributes:
    maximum_items_per_page: 10
    pagination_partial: true

    normalization_context:
      groups: ['get']

    denormalization_context:
      groups: ['post']

    order:
      {published: 'DESC'}

  itemOperations:
    get:
      normalization_context: {groups: ['get-blog-post-with-author']}
    put:
      access_control: is_granted('ROLE_EDITOR', object) or (is_granted('ROLE_WRITER', object) and object.getAuthor() === user)

  collectionOperations:
    get:
      filters: ['app.search_filter', 'app.date_filter', 'app.range_filter', 'app.sort_filter', 'app.property_filter']

      normalization_context: {groups: ['get-blog-post-with-author']}
    post:
      access_control: is_granted('ROLE_WRITER', object)

  properties:
    comment:
      subresource:
        resourceClass: 'App\Entity\Comment'
