App\Entity\Comment:
  attributes:
    normalization_context:
      groups: ['get']

    denormalization_context:
      groups: ['post']

    order:
      {published: 'DESC'}

  itemOperations:
    get:
    put:
      access_control: is_granted('ROLE_EDITOR', object) and (is_granted('ROLE_COMMENTATOR', object) and object.getAuthor() === user)

  collectionOperations:
    get:
    post:
      access_control: is_granted('ROLE_COMMENTATOR', object)
    api_blog_posts_comments_get_subresource:
      method: 'GET'
      normalization_context: {groups: ['get-comment-with-author']}

