App\Entity\Comment:
  attributes:
    normalization_context:
      groups: ['get']

  itemOperations:
    get:
    put:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object) and object.getAuthor() === user

  collectionOperations:
    get:
    post:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object)

