App\Entity\Comment:
  attributes:
#    force_eager: false
    normalization_context:
      groups: ['get']

    denormalization_context:
      groups: ['post']

  itemOperations:
    get:
    put:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object) and object.getAuthor() === user

  collectionOperations:
    get:
    post:
      access_control: is_granted('IS_AUTHENTICATED_FULLY', object)
    api_blog_posts_comments_get_subresource:
      method: 'GET'
      normalization_context: {groups: ['get-comment-with-author']}

