App\Entity\Image:
  attributes:
    order:
      {id: 'DESC'}

  itemOperations:
    get: {}
    put: {}

  collectionOperations:
    get: {}
    post:
      method: 'POST'
      path: '/images'
      controller: 'App\Controller\UploadImageAction'
      defaults:
        _api_receive: false