App\Entity\Image:
  attributes:
    order:
      {id: 'DESC'}
    formats:
      0: "json"
      1: "jsonld"
      form: 'multipart/form-data'

  itemOperations:
    get: {}
    put: {}
    delete:
      access_control: is_granted('ROLE_WRITER', object)

  collectionOperations:
    get: {}
    post:
      method: 'POST'
      path: '/images'
      controller: 'App\Controller\UploadImageAction'
      defaults:
        _api_receive: false